# Generated by Django 2.0.6 on 2018-08-15 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('image', models.ImageField(default='article/image/man_5.png', help_text='160x120', max_length=200, upload_to='article/image/%Y/%m', verbose_name='文章缩略图')),
                ('is_top', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('content', models.TextField(verbose_name='正文')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='名字')),
                ('qq', models.CharField(blank=True, max_length=15, null=True, verbose_name='QQ')),
                ('mobile', models.CharField(blank=True, max_length=15, null=True, verbose_name='手机')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
            ],
            options={
                'verbose_name': '作者',
                'verbose_name_plural': '作者',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('image', models.ImageField(help_text='970x250', max_length=200, upload_to='banner/image/%Y/%m', verbose_name='轮播图')),
                ('url', models.CharField(max_length=200, verbose_name='链接')),
                ('level', models.PositiveSmallIntegerField(default=5, help_text='数字越小越靠前，默认5', verbose_name='级别')),
                ('target', models.PositiveSmallIntegerField(choices=[(1, '当前页'), (2, '新开页')], default=1, verbose_name='打开方式')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='名字')),
            ],
            options={
                'verbose_name': '栏目分类',
                'verbose_name_plural': '栏目分类',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.PositiveSmallIntegerField(choices=[(1, '作者'), (2, '用户')], default=2, verbose_name='角色')),
                ('comment', models.CharField(max_length=100, verbose_name='评论')),
                ('ip', models.GenericIPAddressField(verbose_name='用户IP')),
                ('address', models.CharField(max_length=20, verbose_name='地址')),
                ('qq', models.CharField(max_length=15, verbose_name='QQ')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_article', to='article.Article', verbose_name='文章')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
        migrations.CreateModel(
            name='CommentReplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.PositiveSmallIntegerField(choices=[(1, '作者'), (2, '用户')], default=2, verbose_name='角色')),
                ('ip', models.GenericIPAddressField(verbose_name='用户IP')),
                ('address', models.CharField(max_length=20, verbose_name='地址')),
                ('qq', models.CharField(max_length=15, verbose_name='QQ')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replay_comment', to='article.Comment', verbose_name='评论')),
            ],
            options={
                'verbose_name': '回复评论',
                'verbose_name_plural': '回复评论',
            },
        ),
        migrations.CreateModel(
            name='FriendLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='名字')),
                ('url', models.CharField(max_length=200, unique=True, verbose_name='链接')),
            ],
            options={
                'verbose_name': '友情链接',
                'verbose_name_plural': '友情链接',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='用户IP')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_article', to='article.Article', verbose_name='文章')),
            ],
            options={
                'verbose_name': '点赞',
                'verbose_name_plural': '点赞',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='名字')),
                ('url', models.CharField(max_length=200, unique=True, verbose_name='链接')),
            ],
            options={
                'verbose_name': '合作伙伴',
                'verbose_name_plural': '合作伙伴',
            },
        ),
        migrations.CreateModel(
            name='Read',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_nums', models.IntegerField(default=0, verbose_name='阅读量')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_article', to='article.Article', verbose_name='文章')),
            ],
            options={
                'verbose_name': '阅读',
                'verbose_name_plural': '阅读',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='名字')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_author', to='article.Author', verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_category', to='article.Category', verbose_name='栏目分类'),
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(to='article.Tag', verbose_name='标签'),
        ),
    ]
