# Generated by Django 2.0.6 on 2018-08-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20180815_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(max_length=200, verbose_name='评论'),
        ),
    ]
