# Generated by Django 2.0.6 on 2018-08-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20180815_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentreplay',
            name='replay',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='回复'),
        ),
    ]
