# Generated by Django 2.0.6 on 2018-08-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_commentreplay_replay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreplay',
            name='replay',
            field=models.TextField(max_length=200, verbose_name='回复'),
        ),
    ]
