# Generated by Django 2.0.6 on 2018-08-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20180815_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='发表时间'),
        ),
        migrations.AddField(
            model_name='commentreplay',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='发表时间'),
        ),
    ]
