# Generated by Django 2.0.6 on 2018-08-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20180820_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='banner_image',
            field=models.ImageField(default='article/subject/default.png', help_text='970 x 250', max_length=200, upload_to='article/subject/%Y/%m', verbose_name='大图'),
        ),
    ]
