# Generated by Django 2.0.6 on 2018-08-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_subject_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_publish',
            field=models.BooleanField(default=True, verbose_name='是否发表'),
        ),
    ]
